### ISSUE TITLE
Build Error with `ImGui::ImageButton` Overload in imgui-SFML with ImGui 1.91.4

### ISSUE THREAD

**Issue by ZyN00x** [SFML/imgui-sfml#304] opened 2024-11-04 16:10 UTC
I am encountering a build error in imgui-SFML when using the latest versions of both ImGui and ImGui-SFML. Specifically, I receive multiple errors related to the `ImGui::ImageButton` function overloads in `imgui-SFML.cpp` that indicate an inability to match the provided arguments to a valid function signature.

![image](https://github.com/user-attachments/assets/3e6fe840-5186-4e88-b2ac-ba00c5c27301)

### Environment:

- ImGui Version: 1.91.4 (latest)
- ImGui-SFML Version: 2.6 (latest)
- Compiler: Visual Studio (latest version)
- SFML Version: Latest release
- OS: Windows

**Comment by ChrisThrasher** [comment] 2024-11-04 18:28
Are you compiling with `IMGUI_DISABLE_OBSOLETE_FUNCTIONS` defined?

**Comment by ZyN00x** [comment] 2024-11-04 19:46
No 
![image](https://github.com/user-attachments/assets/18fa5a47-8e15-4026-b5dd-1741541c672a)

**Comment by ChrisThrasher** [comment] 2024-11-04 20:06
https://github.com/SFML/imgui-sfml/actions/runs/11671705896

I added new jobs to the CI pipeline that build ImGui-SFML with ImGui 1.91.4 and I cannot reproduce the errors you're seeing.

**Comment by ZyN00x** [comment] 2024-11-04 21:08
I apologize for taking up your time. It could be a linking issue in my Visual Studio environment, even though I've double-checked it multiple times to ensure there’s no mistake on my end.

**Comment by ChrisThrasher** [comment] 2024-11-05 16:25
Closing until a reproducible example is provided. Happy to reopen once you can provide that.

**Closed by ChrisThrasher** 2024-11-05 16:25 UTC
